#!/usr/bin/env node
// Re-mints an Artifact Registry access token from the developer ADC on every pull.
// Copied from the proven wr-cloud setup script. No `docker login` and no gcloud
// invocation are needed at pull time.
const https = require('https'), fs = require('fs');
if (process.argv[2] !== 'get') { process.exit(0) }
let host = '';
process.stdin.on('data', d => host += d);
process.stdin.on('end', () => {
  const adc = process.env.HOME + '/.config/gcloud/application_default_credentials.json';
  const d = JSON.parse(fs.readFileSync(adc, 'utf8'));
  const body = new URLSearchParams({
    client_id: d.client_id,
    client_secret: d.client_secret,
    refresh_token: d.refresh_token,
    grant_type: 'refresh_token',
  }).toString();
  const req = https.request('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  }, res => {
    let s = '';
    res.on('data', c => s += c);
    res.on('end', () => {
      const t = JSON.parse(s).access_token || '';
      process.stdout.write(JSON.stringify({
        ServerURL: host.trim(), Username: 'oauth2accesstoken', Secret: t,
      }));
    });
  });
  req.on('error', () => process.exit(1));
  req.write(body);
  req.end();
});
